### ISSUE TITLE
Make standalone compiler options match what CMSSW is doing for -ffast-math or similar

### ISSUE THREAD

**Issue by srlantz** [trackreco/cmssw#123]
This is for discussion of the points raised in PR #122. Solutions can be added to that PR if desired.

**Comment by srlantz** [comment]
To summarize and revise slightly what was said in #122, taking into account the subsequent discussion:

The proposal is to change the default compilation for standalone builds to `-Ofast -fno-reciprocal-math -mrecip=none`, since this combination has been approved by CMSSW as not harming reproducibility between AMD and Intel platforms. See cms-sw/cmsdist#8280. This combination of options improves the performance of mkFit by quite a lot: my little test with InitialStep runs almost 20% faster when the above options are provided through `CXXUSERFLAGS`. This is pretty much the same speedup we get with `-ffast-math`, where the latter is what we specify for mkFit in CMS builds.

In general I think our default standalone build should match what we do in the CMS context. So perhaps in both cases we should use `-Ofast -fno-reciprocal-math -mrecip=none`? As @slava77 points out,
> note that this cmsdist PR changes only `ofast-flag` , while in RecoTracker/MkFitCore/BuildFile.xml we use `<flags CXXFLAGS="-ffast-math"/>` instead of `ofast-flag`. Perhaps we should get some consistency.

**Comment by mmasciov** [comment]
@srlantz, @slava77, I performed tests switching the compiler option in `RecoTracker/MkFitCore/Buildfile.xml`.
Results are collected here: http://uaf-10.t2.ucsd.edu/~mmasciov/MIC/testFastMath/
Switching to `ofast-flag` allows for slightly more stable results across different architecture, without noticeable changes in physics or timing performance. Thus, we shall probably just switch to it, if there are no objections?

**Comment by srlantz** [comment]
Sounds good to me. Thank you @mmasciov for running the tests! 

If we make this the default for mkFit, then I think it would be good to change our Makefile.config so the same options become the default for the standalone build at the same time. (It would be a more natural combination than it would have been with PR #122, which became a tiny pull request to CMSSW that was recently merged.)

**Comment by mmasciov** [comment]
@srlantz: PR #124
Is this what you were thinking of?

**Comment by slava77** [comment]
@srlantz 
can this be closed now?

**Comment by srlantz** [comment]
@slava77 - Yes, closing the issue now, PR #124 takes care of this (as @mmasciov pointed out).
