### ISSUE TITLE
Seed hits sanity check

### ISSUE THREAD

**Issue by mmasciov** [trackreco/cmssw#30]
In MkFitOutputConverter, sanity check at [L.279](https://github.com/trackreco/cmssw/blob/CMSSW_11_2_0_mkFit_X/RecoTracker/MkFit/plugins/MkFitOutputConverter.cc#L279) causes a crash related to trackreco/mkFit#321

Solutions (in increasing order of preference):
(1) disable sanity check;
(2) make a separate seed-merging module to produce a new collection of TrajectorySeeds, to be used as input to MkFitOutputConverter (output is a TrackCandidate).

**Comment by slava77** [comment]
why do we have to have a new collection of merged seeds? 

In the long run, it would be indeed better; as a way to more proper integration/absorption of mkfit developments in cmssw.

However, currently, the seed region rebuilding in regular CKF does not imply that the pixel hits have to be only from the seed. So, just it should be enough to keep track of the "parent" seed index during seed merging.

**Comment by mmasciov** [comment]
Closing after further discussion in PR #29: the collection of seeds is the same as it was, hence there is no issue.
